# Generated by Django 4.2.6 on 2023-12-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatememory',
            name='image',
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='uploads/')),
                ('memories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memories.creatememory')),
            ],
        ),
    ]
