# Generated by Django 4.2.6 on 2023-12-03 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_remove_creatememory_image_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='photo',
        ),
        migrations.AddField(
            model_name='photos',
            name='images',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
