# Generated by Django 4.2.6 on 2023-12-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_remove_photos_photo_photos_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatememory',
            name='image1',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='creatememory',
            name='image2',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='creatememory',
            name='image3',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='creatememory',
            name='video',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
